development:
  linkedin_key: xxxxxxxxxxxxxx
  linkedin_secret: xxxxxxxxxxxxxx
  api_host: https://api.linkedin.com
  request_token_path: /uas/oauth/requestToken
  access_token_path: /uas/oauth/accessToken
  authorize_path: /uas/oauth/authorize
  alumni_mckinsey_user: xxxxxxxxxxxxxx
  alumni_mckinsey_password: xxxxxxxxxxxxxx
  alumni_hbs_user: xxxxxxxxxxxxxx
  alumni_hbs_password: xxxxxxxxxxxxxx

test:


production:
  linkedin_key: xxxxxxxxxxxxxx
  linkedin_secret: xxxxxxxxxxxxxx
  api_host: https://api.linkedin.com
  request_token_path: /uas/oauth/requestToken
  access_token_path: /uas/oauth/accessToken
  authorize_path: /uas/oauth/authorize
  alumni_mckinsey_user: xxxxxxxxxxxxxx
  alumni_mckinsey_password: xxxxxxxxxxxxxx
  alumni_hbs_user: xxxxxxxxxxxxxx
  alumni_hbs_password: xxxxxxxxxxxxxx